- name: "Install & configure jenkins_slave"
  hosts: jenkins-slave

  vars:
    master_host: your_master_host
    slave_jenkins_cred_id: 5
    slave_jenkins_username: jenkins
    slave_jenkins_public_key: your_public_key

  roles:
    - role: jenkins_slave
