---
jenkins_home: /var/lib/jenkins
jenkins_hostname: "{{ ansible_host }}"
jenkins_http_port: 8080
jenkins_plugins_state: present
jenkins_plugin_updates_expiration: 86400
jenkins_plugin_timeout: 30
jenkins_plugins_install_dependencies: true
jenkins_updates_url: "https://updates.jenkins.io"
jenkins_url_prefix: ""
jenkins_plugins:
  - git
  - ssh-slaves
  - pipeline
  - pipeline-model-definition
  - pipeline-stage-step
  - job-dsl
  - configuration-as-code-support
  - workflow-aggregator
  - pipeline-maven
  - workflow-job
  - nexus-platform 
