nexus_version: '3.16.2-01'
nexus_package: "nexus-{{ nexus_version }}-unix.tar.gz"
nexus_download_dir: '/tmp'
nexus_backup_dir: '/var/nexus-backup'
nexus_os_group: 'nexus'
nexus_os_user: 'nexus'
nexus_os_max_filedescriptors: 65536
nexus_installation_dir: '/opt'
nexus_data_dir: '/var/nexus'
nexus_timezone: 'UTC' # java timezone
nexus_tmp_dir: '/tmp/nexus'
nexus_script_dir: '{{ nexus_installation_dir }}/nexus-{{ nexus_version }}/etc/scripts'
nexus_default_port: 8081
nexus_default_context_path: '/'
nexus_privileges:
  - name: all-repos-read # used as key to update a privilege
    description: 'Read & Browse access to all repos'
    repository: '*'
    actions:
      - read
      - browse
nexus_roles:
  - id: Developpers 
    name: developers
    description: All developers
    privileges:
      - nx-search-read
      - all-repos-read
    roles: []

_nexus_privilege_defaults:
  type: repository-view
  format: maven2
  actions:
    - read

nexus_blob_split: false
nexus_blob_names:      
  mvn:
    blob: 'default'
  
nexus_repos_maven_proxy:
  - name: central
    remote_url: 'https://repo1.maven.org/maven2/'
    layout_policy: permissive

nexus_repos_maven_hosted:
  - name: private-release
    version_policy: release
    write_policy: allow_once

nexus_repos_maven_group:
  - name: public
    member_repos:
      - central

_nexus_repos_maven_defaults:
  blob_store: "{{ nexus_blob_names.mvn.blob }}"
  strict_content_validation: true
  version_policy: release # release, snapshot or mixed
  layout_policy: strict # strict or permissive
  write_policy: allow_once # allow_once or allow
