jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  mode: NORMAL
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  quietPeriod: 5
  scmCheckoutRetryCount: 0
  securityRealm: # (2)
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        password: "your_pass"
  slaveAgentPort: 50000
  views:
  - all:
      name: "all"
tool:
  git:
    installations:
    - home: "git"
      name: "git"
  jdk:
    defaultProperties:
    - installSource:
        installers:
        - jdkInstaller:
            acceptLicense: false
    installations:
    - home: "/usr/lib/jvm/java-1.8.0-openjdk"
      name: "jdk8"
  maven:
    installations:
    - name: "maven"
      properties:
      - installSource:
          installers:
          - maven:
              id: "3.6.1"
jobs:
  - script: >
      pipelineJob('java') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/zerta664/jenkins.git' }
                        branch '*/master'
                        extensions {}
                    }
                 }
               
              }
          }
      }
    
credentials:
  system:
    domainCredentials:
    - credentials:
      - basicSSHUserPrivateKey:
          description: "key for jenkins_slave"
          id: "5"
          username: jenkins
          privateKeySource:
            directEntry:
              privateKey: |-
                -----BEGIN RSA PRIVATE KEY-----
                <your_key>
                -----END RSA PRIVATE KEY-----

      - usernamePassword:
          description: "nexus-user"
          id: "7"
          username: "admin"
          password: "your_pass"
          scope: GLOBAL
          
unclassified:
  gitSCM:
    createAccountBasedOnEmail: false
  globalNexusConfiguration:
    hideNvsMessage: false
    instanceId: "b381ca5dc2c441b1b263114f6afea94d"
    nxrmConfigs:
    - nxrm3Configuration:
        credentialsId: "7"
        displayName: "Local Nexus"
        id: "LocalHexus"
        internalId: "e8ec1dc7-073d-40e4-9795-f34130977d41"
        serverUrl: "http://127.0.0.1:8081"
