---

#- include: delete_nexus.yml

- include: install_nexus.yml

- include: admin_password_setup.yml

- include: setup_privilege_each.yml
  with_items: "{{ nexus_privileges }}"

- include: setup_role_each.yml
  with_items: "{{ nexus_roles }}"

- include: setup_user_each.yml
  with_items: "{{ nexus_local_users }}"

- include: create_repo_maven_proxy_each.yml
  with_items: "{{ nexus_repos_maven_proxy }}"

- include: create_repo_maven_hosted_each.yml
  with_items: "{{ nexus_repos_maven_hosted }}"

- include: create_repo_maven_group_each.yml
  with_items: "{{ nexus_repos_maven_group }}"
