- name: Install java
  yum:
    name: "{{ java.version }}"
    state: present

- name: Install java-devel
  yum:
    name: "{{ java.version_devel }}"
    state: present

- name: Install git
  yum:
    name: git
    state: present

- name: Download jenkins repo
  get_url:
    url: "{{ jen.repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import gpg key
  rpm_key:
    state: present
    key: "{{ jen.gpg_key }}"

- name: Install jenkins
  yum:
    name: jenkins
    state: present

- name: Change jenkin java option
  lineinfile: 
    dest: "/etc/sysconfig/jenkins"
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS='{{jen.java_options}}'"
  register: result_skip_startup_wizard
 
- name: Start jenkins server
  service:
    name: jenkins
    state: started
    enabled: yes
- wait_for: 
    port: 8080
    delay: 20
   
- name: Install ConfigurationASCodePlugin
  jenkins_plugin:
    name: configuration-as-code
    state: present

- name: Install GitPlugin
  jenkins_plugin:
    name: git
    state: present

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
- wait_for: timeout=20

- name: Enabled ConfigurationASCodePlugin
  jenkins_plugin:
    name: configuration-as-code
    state: enabled

- name: Enabled GitPlugin
  jenkins_plugin:
    name: git
    state: enabled

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
