- name: Install java
  yum:
    name: "{{ java.version }}"
    state: present

- name: Install java-devel
  yum:
    name: "{{ java.version_devel }}"
    state: present

- name: Install git
  yum:
    name: git
    state: present

- name: Download jenkins repo
  get_url:
    url: "{{ jen.repo_url }}"
    dest: /etc/yum.repos.d/jenkins.repo
  become: true

- name: Import gpg key
  rpm_key:
    state: present
    key: "{{ jen.gpg_key }}"

- name: Install jenkins
  yum:
    name: jenkins
    state: present

- name: Change jenkin java option
  lineinfile: 
    dest: "/etc/sysconfig/jenkins"
    regexp: '^JENKINS_JAVA_OPTIONS='
    line: "JENKINS_JAVA_OPTIONS='{{jen.java_options}}'"
  register: result_skip_startup_wizard
 
- name: Start jenkins server
  service:
    name: jenkins
    state: started
    enabled: yes
- wait_for: 
    port: 8080
    delay: 20
   
- name: Install ConfigurationASCodePlugin
  jenkins_plugin:
    name: configuration-as-code
    state: present

- name: Restart Jenkins
  service:
    name: jenkins
    state: restarted
- wait_for: timeout=20

- name: Enabled ConfigurationASCodePlugin
  jenkins_plugin:
    name: configuration-as-code
    state: enabled

- name: Install other Jenkins plugins
  jenkins_plugin:
    name: "{{ item }}"
    jenkins_home: "{{ jenkins_home }}"
    state: "{{ jenkins_plugins_state }}"
    timeout: "{{ jenkins_plugin_timeout }}"
    updates_expiration: "{{ jenkins_plugin_updates_expiration }}"
    updates_url: "{{ jenkins_updates_url }}"
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}"
    with_dependencies: "{{ jenkins_plugins_install_dependencies }}"
  with_items: "{{ jenkins_plugins }}"
  notify: restart jenkins
  tags: ['skip_ansible_lint']
  register: plugin_result
  until: plugin_result is success
  retries: 3
  delay: 2

